apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-db
spec:
  storageClassName: managed
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ledger-db
spec:
  storageClassName: managed
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
