apiVersion: v1
kind: Service
metadata:
  name: ledger-db
  labels:
    application: bank-of-anthos
    component: ledger-db
spec:
  ports:
  - name: tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    application: bank-of-anthos
    component: ledger-db
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-db
  labels:
    application: bank-of-anthos
    component: ledger-db
spec:
  replicas: 1
  selector:
    matchLabels:
      application: bank-of-anthos
      component: ledger-db
  template:
    metadata:
      labels:
        application: bank-of-anthos
        component: ledger-db
    spec:
      containers:
      - name: ledger-db
        image: mdimonte/ledger-db:v0.6.3
        envFrom:
        - configMapRef:
            name: environment-config
        - configMapRef:
            name: ledger-db-config
        - configMapRef:
            name: demo-data-config
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db
          subPath: postgres
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: ledger-db
