apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
stringData:
  mongo-root-username: user
  mongo-root-password: password

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
stringData:
  mongo-express-username: expressuser
  mongo-express-password: expresspassword
