kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db
spec:
  storageClassName: managed
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: configdb
spec:
  storageClassName: managed
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
